# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  quolikeserver:
    image: quolikeserver
    build:
      context: .
      dockerfile: QuoLike.Server/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5196:5196
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
